version: 2.0

jobs:
  build:
    working_directory: ~/promos
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: Update npm
          command: echo 'npm installing'
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install npm wee
          command: npm install

  test:
    working_directory: ~/promos
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: cd promos/src && npm install
      - run: cd promos/src && npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
